In [50]:
# Calculation of complete reporting rates with program and stock data

%matplotlib inline  
# !pip install matplotlib

import pandas as pd
import numpy as np
import pandas_highcharts.core
from sqlalchemy import create_engine
import psycopg2
import matplotlib.pyplot 

# weird construct - if you don't from * import * you have to use datetime.datetime in commands
from datetime import datetime, date, timedelta

from isoweek import Week

import os

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "IMAM.settings")

from django.conf import settings
from home.management.commands.load_data import rename_cols, assign_state_lga_num

import django
django.setup()

# is this line necessary?
from home.models import Program, Stock, Site

In [51]:
# Import Program Data
engine = create_engine(
    'postgresql://{USER}:{PASSWORD}@{HOST}:{PORT}/{NAME}'.format(**settings.DATABASES['default']))
df = pd.read_sql_query("select * from program;", con=engine)


df['year_weeknum'] = zip(df['year'], df['weeknum'])
df['iso_year_weeknum'] = df['year_weeknum'].map(lambda x: Week(x[0], x[1]))

year, week, _ = date.today().isocalendar()
current_week = Week(year, week)

# since how many week this report is about
df['since_x_weeks'] = df['iso_year_weeknum'].map(lambda x: current_week - x)

In [77]:
active_sites = df.query('since_x_weeks<=8').query('siteid>101110001').groupby(['siteid', 'type'])['siteid'].unique()
active_sites

siteid      type
201110007   OTP      [201110007]
201110009   OTP      [201110009]
201110021   OTP      [201110021]
201110026   OTP      [201110026]
201110029   OTP      [201110029]
202110019   OTP      [202110019]
202110021   OTP      [202110021]
202110027   OTP      [202110027]
202110035   OTP      [202110035]
202110068   OTP      [202110068]
202610001   SC       [202610001]
203110002   OTP      [203110002]
203110037   OTP      [203110037]
203110038   OTP      [203110038]
203110043   OTP      [203110043]
203110053   OTP      [203110053]
204110006   OTP      [204110006]
204110014   OTP      [204110014]
204110026   OTP      [204110026]
204110029   OTP      [204110029]
204110035   OTP      [204110035]
205110025   OTP      [205110025]
205110039   OTP      [205110039]
206110004   OTP      [206110004]
206110011   OTP      [206110011]
206110020   OTP      [206110020]
206110032   OTP      [206110032]
206110034   OTP      [206110034]
207110055   OTP      [207110055]
207110082   OTP      [2071

In [75]:
all_sites = df.query('siteid>101110001').groupby(['siteid', 'type'])['siteid'].unique()
all_sites

siteid      type
201110007   OTP      [201110007]
201110009   OTP      [201110009]
201110021   OTP      [201110021]
201110026   OTP      [201110026]
201110029   OTP      [201110029]
201410014   OTP      [201410014]
202110019   OTP      [202110019]
202110021   OTP      [202110021]
202110027   OTP      [202110027]
202110035   OTP      [202110035]
202110068   OTP      [202110068]
202610001   SC       [202610001]
203110002   OTP      [203110002]
203110037   OTP      [203110037]
203110038   OTP      [203110038]
203110043   OTP      [203110043]
203110053   OTP      [203110053]
204110006   OTP      [204110006]
204110014   OTP      [204110014]
204110026   OTP      [204110026]
204110029   OTP      [204110029]
204110035   OTP      [204110035]
205110025   OTP      [205110025]
205110030   OTP      [205110030]
205110039   OTP      [205110039]
206110004   OTP      [206110004]
206110011   OTP      [206110011]
206110020   OTP      [206110020]
206110032   OTP      [206110032]
206110034   OTP      [2061

In [118]:
a = all_sites.to_frame()
a

siteid
siteid     type              
201110007  OTP    [201110007]
201110009  OTP    [201110009]
201110021  OTP    [201110021]
201110026  OTP    [201110026]
201110029  OTP    [201110029]
201410014  OTP    [201410014]
202110019  OTP    [202110019]
202110021  OTP    [202110021]
202110027  OTP    [202110027]
202110035  OTP    [202110035]
202110068  OTP    [202110068]
202610001  SC     [202610001]
203110002  OTP    [203110002]
203110037  OTP    [203110037]
203110038  OTP    [203110038]
203110043  OTP    [203110043]
203110053  OTP    [203110053]
204110006  OTP    [204110006]
204110014  OTP    [204110014]
204110026  OTP    [204110026]
204110029  OTP    [204110029]
204110035  OTP    [204110035]
205110025  OTP    [205110025]
205110030  OTP    [205110030]
205110039  OTP    [205110039]
206110004  OTP    [206110004]
206110011  OTP    [206110011]
206110020  OTP    [206110020]
206110032  OTP    [206110032]
206110034  OTP    [206110034]
...                       ...
3605110058 OTP   [3605110058]
3605110063 OTP   [3605110063]
3605210026 SC    [3605210026]
3607210005 OTP   [3607210005]
3607210063 OTP   [3607210063]
           SC    [3607210063]
3607210081 OTP   [3607210081]
           SC    [3607210081]
3607310003 OTP   [3607310003]
           SC    [3607310003]
3609110002 OTP   [3609110002]
3609110014 OTP   [3609110014]
3609110022 OTP   [3609110022]
3609110026 OTP   [3609110026]
3609110043 OTP   [3609110043]
3609210040 SC    [3609210040]
3611110009 OTP   [3611110009]
3611110018 OTP   [3611110018]
3611110022 OTP   [3611110022]
3611110026 OTP   [3611110026]
3611110031 OTP   [3611110031]
3611110033 OTP   [3611110033]
3611210024 SC    [3611210024]
3611210034 SC    [3611210034]
3613110001 OTP   [3613110001]
3613110010 OTP   [3613110010]
3613110022 OTP   [3613110022]
3613110044 OTP   [3613110044]
3613110051 OTP   [3613110051]
3613210035 SC    [3613210035]

[924 rows x 1 columns]

In [119]:
a = a.drop('siteid', axis=1).reset_index()
a

siteid type
0     201110007  OTP
1     201110009  OTP
2     201110021  OTP
3     201110026  OTP
4     201110029  OTP
5     201410014  OTP
6     202110019  OTP
7     202110021  OTP
8     202110027  OTP
9     202110035  OTP
10    202110068  OTP
11    202610001   SC
12    203110002  OTP
13    203110037  OTP
14    203110038  OTP
15    203110043  OTP
16    203110053  OTP
17    204110006  OTP
18    204110014  OTP
19    204110026  OTP
20    204110029  OTP
21    204110035  OTP
22    205110025  OTP
23    205110030  OTP
24    205110039  OTP
25    206110004  OTP
26    206110011  OTP
27    206110020  OTP
28    206110032  OTP
29    206110034  OTP
..          ...  ...
894  3605110058  OTP
895  3605110063  OTP
896  3605210026   SC
897  3607210005  OTP
898  3607210063  OTP
899  3607210063   SC
900  3607210081  OTP
901  3607210081   SC
902  3607310003  OTP
903  3607310003   SC
904  3609110002  OTP
905  3609110014  OTP
906  3609110022  OTP
907  3609110026  OTP
908  3609110043  OTP
909  3609210040   SC
910  3611110009  OTP
911  3611110018  OTP
912  3611110022  OTP
913  3611110026  OTP
914  3611110031  OTP
915  3611110033  OTP
916  3611210024   SC
917  3611210034   SC
918  3613110001  OTP
919  3613110010  OTP
920  3613110022  OTP
921  3613110044  OTP
922  3613110051  OTP
923  3613210035   SC

[924 rows x 2 columns]

In [104]:
b = active_sites.to_frame().drop('siteid', axis=1).reset_index()
b

siteid type
0     201110007  OTP
1     201110009  OTP
2     201110021  OTP
3     201110026  OTP
4     201110029  OTP
5     202110019  OTP
6     202110021  OTP
7     202110027  OTP
8     202110035  OTP
9     202110068  OTP
10    202610001   SC
11    203110002  OTP
12    203110037  OTP
13    203110038  OTP
14    203110043  OTP
15    203110053  OTP
16    204110006  OTP
17    204110014  OTP
18    204110026  OTP
19    204110029  OTP
20    204110035  OTP
21    205110025  OTP
22    205110039  OTP
23    206110004  OTP
24    206110011  OTP
25    206110020  OTP
26    206110032  OTP
27    206110034  OTP
28    207110055  OTP
29    207110082  OTP
..          ...  ...
805  3605110027  OTP
806  3605110035  OTP
807  3605110051   SC
808  3605110056  OTP
809  3605110058  OTP
810  3605110063  OTP
811  3605210026   SC
812  3607210005  OTP
813  3607210063  OTP
814  3607210081  OTP
815  3607210081   SC
816  3607310003   SC
817  3609110002  OTP
818  3609110014  OTP
819  3609110022  OTP
820  3609110026  OTP
821  3609110043  OTP
822  3609210040   SC
823  3611110009  OTP
824  3611110018  OTP
825  3611110022  OTP
826  3611110026  OTP
827  3611110033  OTP
828  3611210034   SC
829  3613110001  OTP
830  3613110010  OTP
831  3613110022  OTP
832  3613110044  OTP
833  3613110051  OTP
834  3613210035   SC

[835 rows x 2 columns]

In [122]:
zip(a['siteid'], a['type'])

[(201110007, u'OTP'),
 (201110009, u'OTP'),
 (201110021, u'OTP'),
 (201110026, u'OTP'),
 (201110029, u'OTP'),
 (201410014, u'OTP'),
 (202110019, u'OTP'),
 (202110021, u'OTP'),
 (202110027, u'OTP'),
 (202110035, u'OTP'),
 (202110068, u'OTP'),
 (202610001, u'SC'),
 (203110002, u'OTP'),
 (203110037, u'OTP'),
 (203110038, u'OTP'),
 (203110043, u'OTP'),
 (203110053, u'OTP'),
 (204110006, u'OTP'),
 (204110014, u'OTP'),
 (204110026, u'OTP'),
 (204110029, u'OTP'),
 (204110035, u'OTP'),
 (205110025, u'OTP'),
 (205110030, u'OTP'),
 (205110039, u'OTP'),
 (206110004, u'OTP'),
 (206110011, u'OTP'),
 (206110020, u'OTP'),
 (206110032, u'OTP'),
 (206110034, u'OTP'),
 (207110015, u'OTP'),
 (207110055, u'OTP'),
 (207110082, u'OTP'),
 (207110088, u'OTP'),
 (207110089, u'OTP'),
 (207140015, u'OTP'),
 (208110006, u'OTP'),
 (208110021, u'OTP'),
 (208110024, u'OTP'),
 (208110029, u'OTP'),
 (208110033, u'OTP'),
 (209110005, u'OTP'),
 (209110009, u'OTP'),
 (209110011, u'OTP'),
 (209110019, u'OTP'),
 (209110025

In [121]:
len(set(zip(a['siteid'], a['type'])) - set(zip(b['siteid'], b['type'])))

89

In [113]:
b[b.apply(lambda x: x.values not in a.values, axis=1)]

Empty DataFrame
Columns: [siteid, type]
Index: []

In [112]:
pd.concat([a,b,b]).drop_duplicates(keep=False)

index  siteid type
0      0.0     NaN  OTP
1      1.0     NaN  OTP
2      2.0     NaN  OTP
3      3.0     NaN  OTP
4      4.0     NaN  OTP
5      5.0     NaN  OTP
6      6.0     NaN  OTP
7      7.0     NaN  OTP
8      8.0     NaN  OTP
9      9.0     NaN  OTP
10    10.0     NaN  OTP
11    11.0     NaN   SC
12    12.0     NaN  OTP
13    13.0     NaN  OTP
14    14.0     NaN  OTP
15    15.0     NaN  OTP
16    16.0     NaN  OTP
17    17.0     NaN  OTP
18    18.0     NaN  OTP
19    19.0     NaN  OTP
20    20.0     NaN  OTP
21    21.0     NaN  OTP
22    22.0     NaN  OTP
23    23.0     NaN  OTP
24    24.0     NaN  OTP
25    25.0     NaN  OTP
26    26.0     NaN  OTP
27    27.0     NaN  OTP
28    28.0     NaN  OTP
29    29.0     NaN  OTP
..     ...     ...  ...
894  894.0     NaN  OTP
895  895.0     NaN  OTP
896  896.0     NaN   SC
897  897.0     NaN  OTP
898  898.0     NaN  OTP
899  899.0     NaN   SC
900  900.0     NaN  OTP
901  901.0     NaN   SC
902  902.0     NaN  OTP
903  903.0     NaN   SC
904  904.0     NaN  OTP
905  905.0     NaN  OTP
906  906.0     NaN  OTP
907  907.0     NaN  OTP
908  908.0     NaN  OTP
909  909.0     NaN   SC
910  910.0     NaN  OTP
911  911.0     NaN  OTP
912  912.0     NaN  OTP
913  913.0     NaN  OTP
914  914.0     NaN  OTP
915  915.0     NaN  OTP
916  916.0     NaN   SC
917  917.0     NaN   SC
918  918.0     NaN  OTP
919  919.0     NaN  OTP
920  920.0     NaN  OTP
921  921.0     NaN  OTP
922  922.0     NaN  OTP
923  923.0     NaN   SC

[924 rows x 3 columns]

In [81]:
[x for x in all_sites]

[array([201110007]),
 array([201110009]),
 array([201110021]),
 array([201110026]),
 array([201110029]),
 array([201410014]),
 array([202110019]),
 array([202110021]),
 array([202110027]),
 array([202110035]),
 array([202110068]),
 array([202610001]),
 array([203110002]),
 array([203110037]),
 array([203110038]),
 array([203110043]),
 array([203110053]),
 array([204110006]),
 array([204110014]),
 array([204110026]),
 array([204110029]),
 array([204110035]),
 array([205110025]),
 array([205110030]),
 array([205110039]),
 array([206110004]),
 array([206110011]),
 array([206110020]),
 array([206110032]),
 array([206110034]),
 array([207110015]),
 array([207110055]),
 array([207110082]),
 array([207110088]),
 array([207110089]),
 array([207140015]),
 array([208110006]),
 array([208110021]),
 array([208110024]),
 array([208110029]),
 array([208110033]),
 array([209110005]),
 array([209110009]),
 array([209110011]),
 array([209110019]),
 array([209110025]),
 array([210110016]),
 array([21011

In [83]:
len(set([x[0] for x in all_sites]) - set([x[0] for x in active_sites]))

77

In [85]:
len(all_sites) - len(active_sites)

89

In [84]:
len(set([x[0] for x in all_sites]))

899

In [52]:
df.query('since_x_weeks>0').query('since_x_weeks<=8').query('siteid>101110001').groupby(['siteid', 'type'])['weeknum'].unique()


siteid      type
201110007   OTP     [12, 11, 13, 18, 17, 16, 15, 14]
201110009   OTP     [13, 12, 11, 14, 15, 17, 16, 18]
201110021   OTP                             [12, 11]
201110026   OTP                             [11, 12]
201110029   OTP                             [11, 12]
202110019   OTP             [17, 16, 15, 13, 12, 11]
202110021   OTP         [12, 11, 15, 14, 13, 16, 17]
202110027   OTP                             [11, 12]
202110035   OTP         [11, 14, 13, 12, 17, 16, 15]
202110068   OTP     [16, 11, 15, 14, 17, 12, 13, 18]
202610001   SC      [11, 18, 17, 16, 15, 14, 13, 12]
203110002   OTP     [13, 15, 14, 12, 11, 16, 18, 17]
203110037   OTP     [12, 15, 14, 17, 16, 13, 11, 18]
203110038   OTP     [12, 11, 13, 17, 16, 15, 14, 18]
203110043   OTP     [13, 12, 15, 14, 11, 17, 16, 18]
203110053   OTP             [13, 11, 12, 16, 14, 15]
204110006   OTP     [16, 12, 11, 14, 13, 15, 17, 18]
204110014   OTP             [15, 12, 11, 16, 13, 14]
204110026   OTP         [12, 

In [69]:
report = df.query('since_x_weeks>0').query('since_x_weeks<=8').query('siteid>101110001').groupby(['siteid', 'type'])['weeknum'].unique().map(
    lambda x: list(sorted(set(range(week - 8, week)) - set(x)))).to_frame()

report

weeknum
siteid     type                              
201110007  OTP                             []
201110009  OTP                             []
201110021  OTP       [13, 14, 15, 16, 17, 18]
201110026  OTP       [13, 14, 15, 16, 17, 18]
201110029  OTP       [13, 14, 15, 16, 17, 18]
202110019  OTP                       [14, 18]
202110021  OTP                           [18]
202110027  OTP       [13, 14, 15, 16, 17, 18]
202110035  OTP                           [18]
202110068  OTP                             []
202610001  SC                              []
203110002  OTP                             []
203110037  OTP                             []
203110038  OTP                             []
203110043  OTP                             []
203110053  OTP                       [17, 18]
204110006  OTP                             []
204110014  OTP                       [17, 18]
204110026  OTP                           [18]
204110029  OTP                           [18]
204110035  OTP                       [17, 18]
205110025  OTP   [12, 13, 14, 15, 16, 17, 18]
205110039  OTP                       [17, 18]
206110004  OTP                             []
206110011  OTP                             []
206110020  OTP                             []
206110032  OTP                       [17, 18]
206110034  OTP                             []
207110055  OTP                             []
207110082  OTP                           [18]
...                                       ...
3605110027 OTP                             []
3605110035 OTP                             []
3605110051 SC                              []
3605110056 OTP           [14, 15, 16, 17, 18]
3605110058 OTP                             []
3605110063 OTP                             []
3605210026 SC                            [18]
3607210005 OTP                             []
3607210063 OTP                             []
3607210081 OTP                             []
           SC                            [18]
3607310003 SC                        [17, 18]
3609110002 OTP                             []
3609110014 OTP                           [18]
3609110022 OTP                           [18]
3609110026 OTP                             []
3609110043 OTP                             []
3609210040 SC                            [18]
3611110009 OTP                           [18]
3611110018 OTP               [15, 16, 17, 18]
3611110022 OTP                             []
3611110026 OTP           [14, 15, 16, 17, 18]
3611110033 OTP                           [18]
3611210034 SC                              []
3613110001 OTP                       [17, 18]
3613110010 OTP                           [18]
3613110022 OTP                             []
3613110044 OTP                             []
3613110051 OTP                           [18]
3613210035 SC        [13, 14, 15, 16, 17, 18]

[835 rows x 1 columns]

In [54]:
report.reset_index()

siteid type                       weeknum
0     201110007  OTP                            []
1     201110009  OTP                            []
2     201110021  OTP      [13, 14, 15, 16, 17, 18]
3     201110026  OTP      [13, 14, 15, 16, 17, 18]
4     201110029  OTP      [13, 14, 15, 16, 17, 18]
5     202110019  OTP                      [14, 18]
6     202110021  OTP                          [18]
7     202110027  OTP      [13, 14, 15, 16, 17, 18]
8     202110035  OTP                          [18]
9     202110068  OTP                            []
10    202610001   SC                            []
11    203110002  OTP                            []
12    203110037  OTP                            []
13    203110038  OTP                            []
14    203110043  OTP                            []
15    203110053  OTP                      [17, 18]
16    204110006  OTP                            []
17    204110014  OTP                      [17, 18]
18    204110026  OTP                          [18]
19    204110029  OTP                          [18]
20    204110035  OTP                      [17, 18]
21    205110025  OTP  [12, 13, 14, 15, 16, 17, 18]
22    205110039  OTP                      [17, 18]
23    206110004  OTP                            []
24    206110011  OTP                            []
25    206110020  OTP                            []
26    206110032  OTP                      [17, 18]
27    206110034  OTP                            []
28    207110055  OTP                            []
29    207110082  OTP                          [18]
..          ...  ...                           ...
805  3605110027  OTP                            []
806  3605110035  OTP                            []
807  3605110051   SC                            []
808  3605110056  OTP          [14, 15, 16, 17, 18]
809  3605110058  OTP                            []
810  3605110063  OTP                            []
811  3605210026   SC                          [18]
812  3607210005  OTP                            []
813  3607210063  OTP                            []
814  3607210081  OTP                            []
815  3607210081   SC                          [18]
816  3607310003   SC                      [17, 18]
817  3609110002  OTP                            []
818  3609110014  OTP                          [18]
819  3609110022  OTP                          [18]
820  3609110026  OTP                            []
821  3609110043  OTP                            []
822  3609210040   SC                          [18]
823  3611110009  OTP                          [18]
824  3611110018  OTP              [15, 16, 17, 18]
825  3611110022  OTP                            []
826  3611110026  OTP          [14, 15, 16, 17, 18]
827  3611110033  OTP                          [18]
828  3611210034   SC                            []
829  3613110001  OTP                      [17, 18]
830  3613110010  OTP                          [18]
831  3613110022  OTP                            []
832  3613110044  OTP                            []
833  3613110051  OTP                          [18]
834  3613210035   SC      [13, 14, 15, 16, 17, 18]

[835 rows x 3 columns]

In [55]:
contacts = pd.read_sql_query("select * from registration;", con=engine)

In [56]:
contacts

contact_uuid             urn  \
0     935b9363-1db3-431c-ab7c-1fffaa44819b  +2348035946219   
1     6afd0807-35a0-4707-8f9c-52bd137fd5fe  +2348080440504   
2     cb10403c-06d3-4965-92d6-06736aa890f8  +2348108130945   
3     9b407705-f5db-4819-98a9-121ab41867ce  +2348038489130   
4     17ec92bb-b715-4391-9506-331310b65dfb  +2348063446207   
5     1d425221-b5a4-47e9-91df-b896868db4a6  +2348069142125   
6     b830de47-a791-4632-b729-761c966993a4  +2348025770177   
7     58cb9480-0994-46f7-a287-dd123ee7e91c  +2348137974197   
8     c1fd47eb-493f-4687-9d32-fd04dce026b3  +2347064831294   
9     7f6b75d7-fb31-4338-9a98-6ca141ee2e42  +2347013493266   
10    5454403f-ed01-4160-a040-bfba1011b93a  +2348167771871   
11    51f08a76-da73-4424-8f40-1d8ff19720c5  +2348066459159   
12    c3ee08c9-59a1-4396-9339-281493e47225  +2348069246777   
13    1ff6efff-4f06-40ef-8218-60cb8dcb9824  +2348022084240   
14    d39f5ecf-573b-427d-a42f-c9c4b7bb077c  +2347085888487   
15    745aba2b-089f-470f-bdd5-dbbbd065de60  +2348094912924   
16    35704252-703c-4f9f-a147-37a742f68adb  +2348138144147   
17    1140657f-4d38-4dd8-99c8-c190d83f9ca5  +2347034230787   
18    8364b4a6-cbb1-4b8c-9b72-b80f917d7303  +2347037690402   
19    cc6c9344-b82b-4c42-a43b-bc412d08a9d0  +2348092944860   
20    37a3b8af-73f5-4617-95fe-765f84c735eb  +2348063404704   
21    99cf7d6f-37d7-40fc-9a50-f03847d07da2  +2348065356507   
22    c0ff77c6-7fbc-48ef-881a-51a62ad4235f  +2348086612866   
23    9a72cfbb-ab26-4ad7-909e-c705440febaf  +2348162301007   
24    509b31ad-6758-406f-86c2-7c31dbca18bf  +2348067206623   
25    fcfc6f1f-6290-45a1-a6e9-484aa9efdc46  +2348032603406   
26    a51f637d-1cb4-44fc-8694-5c9b5f1ed6a8  +2348094622322   
27    86f2faf4-3200-412c-b715-902054be1df5  +2347037855655   
28    face4160-42fa-47a8-909b-744ebc79314c  +2348035080174   
29    c8ea135f-6970-465b-a609-2085e3298691  +2347010231024   
...                                    ...             ...   
2754  6d52005a-b2d5-4411-9a0c-148614f2285e  +2347086422774   
2755  6ad0b233-d6aa-4880-822d-ef5f0a7ec895  +2348026808341   
2756  aa828f2f-de86-43c6-bfe3-69448a7ff717  +2347039798025   
2757  7cc91b59-f58d-47eb-8e7c-6a1b1b651632  +2348107915859   
2758  9eddb201-97d2-4dca-87eb-72c659ee0fc7  +2347067702820   
2759  8f863222-79b8-4ba2-9b6f-bc3e0f0c5238  +2347060756079   
2760  a554f343-4d7f-41e1-86d6-a5dabd8cfb7b  +2347032543102   
2761  2e138de0-d2ac-4afb-810c-5c0e37d8fb9f  +2348028655791   
2762  dfb9cf80-163d-45a4-8651-3f946d6e6f24  +2348032812573   
2763  23ac2b43-3a78-4dd8-bda0-9f538affc77e  +2348068038260   
2764  8b7564fe-e544-4947-8d16-5b30861094d4  +2348064792685   
2765  3e01905e-0da7-4f4a-aa65-146bed550f3f  +2348062180103   
2766  1a635643-b49e-472e-8c5b-929c24feb83c  +2348038228855   
2767  ecd695fd-a605-4df1-8b81-8b84a4aa541f  +2348065584931   
2768  a0cf23bd-d1cb-47a9-b7a2-c49ca2c9d0dc  +2348039775801   
2769  bfd04688-2ef6-442a-9b78-f8fb735ed4db  +2348034592324   
2770  12404b53-a3a4-40f5-bb74-2280e8b6eb50  +2348062523062   
2771  1af5feba-27d8-4ceb-859a-8d657eea44ce  +2348033352521   
2772  8802fb35-de5a-42ae-8e3a-8c37186e0551  +2347031617472   
2773  dc756d04-2672-488d-8b49-050c1eb485df  +2348082373235   
2774  e550edf2-b3c4-4707-b160-48a44d092eb4  +2348022451493   
2775  dbbc6f13-2ffa-4fda-bde0-4b612af5ae64  +2348025474388   
2776  3e646bfc-ae60-4857-9644-6f27feefc3c9  +2348024674289   
2777  8042360f-df52-4b95-bb31-3afaa66b3192  +2348082978269   
2778  6889e5d2-ff15-4c6d-be13-c32dc4d26233  +2347030483326   
2779  28f3d320-7d0e-4296-901d-b3187e02fe0c  +2348039264046   
2780  466bb812-0b23-451e-88e6-d9db370ea569  +2348160841050   
2781  fb219cfa-25ce-43a5-9710-aa90902e8874  +2347034357400   
2782  b8d6b3a9-e33b-4c2d-ab4a-ae2d685b4cb5  +2348065453767   
2783  eb516609-dab6-4b8e-8f2e-bbce0bca93ca  +2348067012918   

                       name groups      siteid  type  \
0          Sunusi Abubakar.         1703110032   OTP   
1       Ibrahim Inuwa Lano.                 16  None   
2             Bal

In [57]:
reminders = pd.merge(report.reset_index(), contacts, on=['siteid', 'type'])
reminders

siteid type                   weeknum  \
0      201110007  OTP                        []   
1      201110007  OTP                        []   
2      201110009  OTP                        []   
3      201110009  OTP                        []   
4      201110021  OTP  [13, 14, 15, 16, 17, 18]   
5      201110021  OTP  [13, 14, 15, 16, 17, 18]   
6      201110026  OTP  [13, 14, 15, 16, 17, 18]   
7      201110026  OTP  [13, 14, 15, 16, 17, 18]   
8      201110029  OTP  [13, 14, 15, 16, 17, 18]   
9      201110029  OTP  [13, 14, 15, 16, 17, 18]   
10     202110019  OTP                  [14, 18]   
11     202110019  OTP                  [14, 18]   
12     202110021  OTP                      [18]   
13     202110021  OTP                      [18]   
14     202110021  OTP                      [18]   
15     202110021  OTP                      [18]   
16     202110027  OTP  [13, 14, 15, 16, 17, 18]   
17     202110027  OTP  [13, 14, 15, 16, 17, 18]   
18     202110035  OTP                      [18]   
19     202110035  OTP                      [18]   
20     202110035  OTP                      [18]   
21     202110035  OTP                      [18]   
22     202110068  OTP                        []   
23     202110068  OTP                        []   
24     202110068  OTP                        []   
25     202610001   SC                        []   
26     203110002  OTP                        []   
27     203110002  OTP                        []   
28     203110002  OTP                        []   
29     203110037  OTP                        []   
...          ...  ...                       ...   
2034  3609110043  OTP                        []   
2035  3609210040   SC                      [18]   
2036  3609210040   SC                      [18]   
2037  3611110009  OTP                      [18]   
2038  3611110009  OTP                      [18]   
2039  3611110018  OTP          [15, 16, 17, 18]   
2040  3611110018  OTP          [15, 16, 17, 18]   
2041  3611110018  OTP          [15, 16, 17, 18]   
2042  3611110022  OTP                        []   
2043  3611110022  OTP                        []   
2044  3611110022  OTP                        []   
2045  3611110026  OTP      [14, 15, 16, 17, 18]   
2046  3611110026  OTP      [14, 15, 16, 17, 18]   
2047  3611110026  OTP      [14, 15, 16, 17, 18]   
2048  3611110033  OTP                      [18]   
2049  3611110033  OTP                      [18]   
2050  3611210034   SC                        []   
2051  3611210034   SC                        []   
2052  3613110001  OTP                  [17, 18]   
2053  3613110001  OTP                  [17, 18]   
2054  3613110001  OTP                  [17, 18]   
2055  3613110010  OTP                      [18]   
2056  3613110010  OTP                      [18]   
2057  3613110022  OTP                        []   
2058  3613110022  OTP                        []   
2059  3613110044  OTP                        []   
2060  3613110044  OTP                        []   
2061  3613110051  OTP                      [18]   
2062  3613110051  OTP                      [18]   
2063  3613210035   SC  [13, 14, 15, 16, 17, 18]   

                              contact_uuid             urn  \
0     70eaa1cc-40ee-4323-aed3-647767bffcda  +2348134107585   
1     c004920d-9463-4176-a672-ce4332583b9d  +2349021245510   
2     3857d121-cfef-4b64-afb6-74022862f6ea  +2348160018409   
3     1a4b900e-803e-43bb-a786-cf8e60435155  +2348165753101   
4     ecb54d20-74cd-471d-a4a7-0f0208b88bdd  +2348092914506   
5     7a9cdd08-35d3-481e-a2c1-12999890a6dd  +2349091141475   
6     8ffd3195-a53c-4069-b394-ab665a0a64d0  +2348029967848   
7     e890a957-cf10-4da0-b538-8a03a6c7844f  +2348022022110   
8     681f91d1-ca59-4d32-bdd5-0081357bcf54  +2347080871500   
9     ba1f390c-8a0d-4cba-b588-43b6bec664c8  +2349023158231   
10    b679ca25-db75-4137-90e5-8dfbc56bfef2  +2348086762757   
11    bd5385d4-5953-4a65-829d-1ffd25ae3bb9  +2347033992688   
12    2ab2d7c2-b1a5-4cec-857a-a0d06ddaf77

In [58]:
reminders['number_of_missing_week'] = reminders['weeknum'].map(len)
reminders

siteid type                   weeknum  \
0      201110007  OTP                        []   
1      201110007  OTP                        []   
2      201110009  OTP                        []   
3      201110009  OTP                        []   
4      201110021  OTP  [13, 14, 15, 16, 17, 18]   
5      201110021  OTP  [13, 14, 15, 16, 17, 18]   
6      201110026  OTP  [13, 14, 15, 16, 17, 18]   
7      201110026  OTP  [13, 14, 15, 16, 17, 18]   
8      201110029  OTP  [13, 14, 15, 16, 17, 18]   
9      201110029  OTP  [13, 14, 15, 16, 17, 18]   
10     202110019  OTP                  [14, 18]   
11     202110019  OTP                  [14, 18]   
12     202110021  OTP                      [18]   
13     202110021  OTP                      [18]   
14     202110021  OTP                      [18]   
15     202110021  OTP                      [18]   
16     202110027  OTP  [13, 14, 15, 16, 17, 18]   
17     202110027  OTP  [13, 14, 15, 16, 17, 18]   
18     202110035  OTP                      [18]   
19     202110035  OTP                      [18]   
20     202110035  OTP                      [18]   
21     202110035  OTP                      [18]   
22     202110068  OTP                        []   
23     202110068  OTP                        []   
24     202110068  OTP                        []   
25     202610001   SC                        []   
26     203110002  OTP                        []   
27     203110002  OTP                        []   
28     203110002  OTP                        []   
29     203110037  OTP                        []   
...          ...  ...                       ...   
2034  3609110043  OTP                        []   
2035  3609210040   SC                      [18]   
2036  3609210040   SC                      [18]   
2037  3611110009  OTP                      [18]   
2038  3611110009  OTP                      [18]   
2039  3611110018  OTP          [15, 16, 17, 18]   
2040  3611110018  OTP          [15, 16, 17, 18]   
2041  3611110018  OTP          [15, 16, 17, 18]   
2042  3611110022  OTP                        []   
2043  3611110022  OTP                        []   
2044  3611110022  OTP                        []   
2045  3611110026  OTP      [14, 15, 16, 17, 18]   
2046  3611110026  OTP      [14, 15, 16, 17, 18]   
2047  3611110026  OTP      [14, 15, 16, 17, 18]   
2048  3611110033  OTP                      [18]   
2049  3611110033  OTP                      [18]   
2050  3611210034   SC                        []   
2051  3611210034   SC                        []   
2052  3613110001  OTP                  [17, 18]   
2053  3613110001  OTP                  [17, 18]   
2054  3613110001  OTP                  [17, 18]   
2055  3613110010  OTP                      [18]   
2056  3613110010  OTP                      [18]   
2057  3613110022  OTP                        []   
2058  3613110022  OTP                        []   
2059  3613110044  OTP                        []   
2060  3613110044  OTP                        []   
2061  3613110051  OTP                      [18]   
2062  3613110051  OTP                      [18]   
2063  3613210035   SC  [13, 14, 15, 16, 17, 18]   

                              contact_uuid             urn  \
0     70eaa1cc-40ee-4323-aed3-647767bffcda  +2348134107585   
1     c004920d-9463-4176-a672-ce4332583b9d  +2349021245510   
2     3857d121-cfef-4b64-afb6-74022862f6ea  +2348160018409   
3     1a4b900e-803e-43bb-a786-cf8e60435155  +2348165753101   
4     ecb54d20-74cd-471d-a4a7-0f0208b88bdd  +2348092914506   
5     7a9cdd08-35d3-481e-a2c1-12999890a6dd  +2349091141475   
6     8ffd3195-a53c-4069-b394-ab665a0a64d0  +2348029967848   
7     e890a957-cf10-4da0-b538-8a03a6c7844f  +2348022022110   
8     681f91d1-ca59-4d32-bdd5-0081357bcf54  +2347080871500   
9     ba1f390c-8a0d-4cba-b588-43b6bec664c8  +2349023158231   
10    b679ca25-db75-4137-90e5-8dfbc56bfef2  +2348086762757   
11    bd5385d4-5953-4a65-829d-1ffd25ae3bb9  +2347033992688   
12    2ab2d7c2-b1a5-4cec-857a-a0d06ddaf77

In [59]:
reminders.query('number_of_missing_week > 0')

siteid type                   weeknum  \
4      201110021  OTP  [13, 14, 15, 16, 17, 18]   
5      201110021  OTP  [13, 14, 15, 16, 17, 18]   
6      201110026  OTP  [13, 14, 15, 16, 17, 18]   
7      201110026  OTP  [13, 14, 15, 16, 17, 18]   
8      201110029  OTP  [13, 14, 15, 16, 17, 18]   
9      201110029  OTP  [13, 14, 15, 16, 17, 18]   
10     202110019  OTP                  [14, 18]   
11     202110019  OTP                  [14, 18]   
12     202110021  OTP                      [18]   
13     202110021  OTP                      [18]   
14     202110021  OTP                      [18]   
15     202110021  OTP                      [18]   
16     202110027  OTP  [13, 14, 15, 16, 17, 18]   
17     202110027  OTP  [13, 14, 15, 16, 17, 18]   
18     202110035  OTP                      [18]   
19     202110035  OTP                      [18]   
20     202110035  OTP                      [18]   
21     202110035  OTP                      [18]   
38     203110053  OTP                  [17, 18]   
39     203110053  OTP                  [17, 18]   
42     204110014  OTP                  [17, 18]   
43     204110014  OTP                  [17, 18]   
44     204110014  OTP                  [17, 18]   
45     204110026  OTP                      [18]   
46     204110026  OTP                      [18]   
47     204110029  OTP                      [18]   
48     204110029  OTP                      [18]   
49     204110035  OTP                  [17, 18]   
50     204110035  OTP                  [17, 18]   
51     204110035  OTP                  [17, 18]   
...          ...  ...                       ...   
2017  3607210081   SC                      [18]   
2018  3607310003   SC                  [17, 18]   
2019  3607310003   SC                  [17, 18]   
2020  3607310003   SC                  [17, 18]   
2023  3609110014  OTP                      [18]   
2024  3609110014  OTP                      [18]   
2025  3609110014  OTP                      [18]   
2026  3609110022  OTP                      [18]   
2027  3609110022  OTP                      [18]   
2028  3609110022  OTP                      [18]   
2035  3609210040   SC                      [18]   
2036  3609210040   SC                      [18]   
2037  3611110009  OTP                      [18]   
2038  3611110009  OTP                      [18]   
2039  3611110018  OTP          [15, 16, 17, 18]   
2040  3611110018  OTP          [15, 16, 17, 18]   
2041  3611110018  OTP          [15, 16, 17, 18]   
2045  3611110026  OTP      [14, 15, 16, 17, 18]   
2046  3611110026  OTP      [14, 15, 16, 17, 18]   
2047  3611110026  OTP      [14, 15, 16, 17, 18]   
2048  3611110033  OTP                      [18]   
2049  3611110033  OTP                      [18]   
2052  3613110001  OTP                  [17, 18]   
2053  3613110001  OTP                  [17, 18]   
2054  3613110001  OTP                  [17, 18]   
2055  3613110010  OTP                      [18]   
2056  3613110010  OTP                      [18]   
2061  3613110051  OTP                      [18]   
2062  3613110051  OTP                      [18]   
2063  3613210035   SC  [13, 14, 15, 16, 17, 18]   

                              contact_uuid             urn  \
4     ecb54d20-74cd-471d-a4a7-0f0208b88bdd  +2348092914506   
5     7a9cdd08-35d3-481e-a2c1-12999890a6dd  +2349091141475   
6     8ffd3195-a53c-4069-b394-ab665a0a64d0  +2348029967848   
7     e890a957-cf10-4da0-b538-8a03a6c7844f  +2348022022110   
8     681f91d1-ca59-4d32-bdd5-0081357bcf54  +2347080871500   
9     ba1f390c-8a0d-4cba-b588-43b6bec664c8  +2349023158231   
10    b679ca25-db75-4137-90e5-8dfbc56bfef2  +2348086762757   
11    bd5385d4-5953-4a65-829d-1ffd25ae3bb9  +2347033992688   
12    2ab2d7c2-b1a5-4cec-857a-a0d06ddaf776  +2348103586218   
13    4e09ed3b-3131-4dd0-833d-2f0b6b72e98d  +2348088482226   
14    2a9d3e03-aa86-441f-9e88-d1be411af60b  +2347033046946   
15    bfcecffc-a6ff-481b-b521-905137c52c0d  +2348126658516   
16    d5011ff1-8d59-4733-bb8d-eec43020b7e

In [60]:
set([tuple(sorted(x)) for x in reminders.query('number_of_missing_week > 0').weeknum])

{(11,),
 (11, 12, 13),
 (11, 12, 13, 14),
 (11, 12, 13, 14, 15, 16),
 (11, 12, 13, 14, 15, 16, 17),
 (11, 12, 13, 14, 15, 18),
 (11, 12, 13, 14, 17, 18),
 (11, 12, 13, 15),
 (11, 12, 13, 17),
 (11, 12, 13, 17, 18),
 (11, 12, 14, 15, 16, 17, 18),
 (11, 12, 15, 16, 17, 18),
 (11, 12, 17, 18),
 (11, 12, 18),
 (11, 13, 18),
 (11, 14, 15, 16, 17, 18),
 (11, 15, 16, 17, 18),
 (11, 17, 18),
 (11, 18),
 (12, 13, 14),
 (12, 13, 14, 15, 16, 17, 18),
 (12, 13, 14, 17, 18),
 (12, 13, 16, 17, 18),
 (12, 14, 16, 17, 18),
 (12, 16),
 (12, 18),
 (13,),
 (13, 14, 15, 16, 17, 18),
 (13, 15, 16, 17, 18),
 (13, 16, 17, 18),
 (13, 17, 18),
 (13, 18),
 (14,),
 (14, 15, 16, 17, 18),
 (14, 15, 18),
 (14, 16, 17, 18),
 (14, 17, 18),
 (14, 18),
 (15,),
 (15, 16, 17, 18),
 (15, 17, 18),
 (16,),
 (16, 17, 18),
 (16, 18),
 (17,),
 (17, 18),
 (18,)}